### ISSUE TITLE
Subject Code and Level

### ISSUE THREAD

**Issue by cliftonc** [stichtingsem/technology-prototype#39]
@niesink @mcginkel - we should get together (either sync or async!) and agree how to approach this:

It needs to exist in a lot of places;

- The SIS: https://github.com/stichtingsem/technology-prototype/blob/master/reference/sisdata.v1.yaml#L233-L264
- The LA: https://github.com/stichtingsem/technology-prototype/blob/learning-application-catalogue/reference/catalogue.v1.yaml#L281-L292
- The MP: https://github.com/stichtingsem/technology-prototype/blob/master/reference/entitlement.v1.yaml#L304-L329

We need to agree a common way of structuring these and keep it consistent?

**Comment by mcginkel** [comment]
I would use 4 things:

Level: determine for what studylevel it is: like HAVO-1, VWO-4, etc (this would be an official list)
Study: study name used in the school: "Technasium-1" (which is actually HAVO-1)(or HAVO-1 and VWO-1)
SubjectCode: official code from goverment (see https://wetten.overheid.nl/BWBR0043849/2020-08-01)
SubjectName: Name of the subject as used on the school

**Comment by niesink** [comment]
I agree that the inclusion of the year/grade is probably a good idea, though we should acknowledge that this can differ between subjects, as can the level. For instance a student enrolled into the 5th year of 0393 (HAVO Natuur & Gezondheid) can take a couple of subjects at VWO-6 level.

Related to this I'm not sure I understand what is meant by 'Study' in this proposal. Are we talking about the specific education ('opleiding') the student is enrolled in or the level at which a certain subject is followed?

**Comment by mcginkel** [comment]
In the meeting of 22 feb we redefined it as course.
So now we have
 
Level: determine for what studylevel it is: like HAVO-1, VWO-4, etc (this would be an official list)
SubjectCode: official code from goverment (see https://wetten.overheid.nl/BWBR0043849/2020-08-01)
SubjectName: Name of the subject as used on the school
Course: School name of the Level/couse/study. 
               example 'Technasium, etc.' This gives schools a way to name the course how they want it, wile we still have a link with the official level
CourseYear: year of the course : start with 1

so a student in your example is indeed enrolled in the course "HAVO Natuur & Gezondheid", with courseYear "5", following a SubjectName "Italiaans", SubjectCode "1067" at level "VWO-6"

If you combine all subjectChoices chich have this information you can detect what learning material is needed for this student, what studies or courses the student is enrolled in and if the school uses group based education: what groups is this student part of. 
The link between group and subject becomes more and more blurred or more flexible due to individual rosters and "studiekeuzetijd"

**Comment by mcginkel** [comment]
So we have this on SIS data and Product. We also need to same on the entitlement, otherwise we cannot make a match in LMS or LA.
